CREATE TABLE m5_agent_runs (
    id TEXT PRIMARY KEY,
    trial_id TEXT NOT NULL REFERENCES trials(id),
    request_id TEXT NOT NULL,
    user_text TEXT NOT NULL CHECK (length(user_text) BETWEEN 1 AND 2000),
    status TEXT NOT NULL CHECK (status IN ('pending','ok','provider_error','agent_error')),
    requested_model TEXT NOT NULL,
    response_model TEXT,
    provider TEXT,
    prompt_version TEXT NOT NULL,
    prompt_sha256 TEXT NOT NULL,
    temperature REAL NOT NULL CHECK (temperature >= 0 AND temperature <= 2),
    max_steps INTEGER NOT NULL CHECK (max_steps > 0),
    query_json TEXT CHECK (query_json IS NULL OR json_valid(query_json)),
    trajectory_json TEXT CHECK (trajectory_json IS NULL OR json_valid(trajectory_json)),
    final_text TEXT,
    termination TEXT,
    error_code TEXT,
    error_message TEXT,
    llm_ms REAL CHECK (llm_ms IS NULL OR llm_ms >= 0),
    tool_ms REAL CHECK (tool_ms IS NULL OR tool_ms >= 0),
    total_ms REAL CHECK (total_ms IS NULL OR total_ms >= 0),
    llm_calls INTEGER CHECK (llm_calls IS NULL OR llm_calls >= 0),
    tool_calls INTEGER CHECK (tool_calls IS NULL OR tool_calls >= 0),
    input_tokens INTEGER CHECK (input_tokens IS NULL OR input_tokens >= 0),
    output_tokens INTEGER CHECK (output_tokens IS NULL OR output_tokens >= 0),
    started_ms INTEGER NOT NULL,
    finished_ms INTEGER,
    UNIQUE (trial_id, request_id)
);
CREATE INDEX m5_agent_runs_trial ON m5_agent_runs(trial_id, started_ms);
